'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { GoogleOAuthProvider } from '@react-oauth/google';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import Header from './components/header/Header';
import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();
  return (
    <html lang='en'>
      <body className={inter.className}>
        <GoogleOAuthProvider clientId='330840049318-9qlucbhqlqgh6caou7d1r30ggo8f1ca3.apps.googleusercontent.com'>
          <QueryClientProvider client={queryClient}>
            <Header />
            {children}
            <ReactQueryDevtools initialIsOpen={false} />
          </QueryClientProvider>

          {/* <ReactQueryDevtools initialIsOpen={false} /> */}
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
